controller_manager_ns: controller_manager
controller_list:
  - name: armstrong_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [Joint_1, Joint_2, Joint_3, Joint_4, Joint_5, Joint_6]

  - name: armstrong_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [Joint_7]
