controller_list:
  - name: fake_Arm_controller
    joints:
      - First_Joint_Axis
      - Second_Joint_Axis
      - Third_Joint_Axis
      - Fourth_Joint_Axis
      - Fifth_Joint_Axis
  - name: fake_Gripper_controller
    joints:
      - Seventh_Joint_Axis
      - Sixth_Joint_Axis